spring:
  application:
    name: back-service

  datasource:
    url: jdbc:mysql://192.168.1.135:3306/smart_study?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  cloud:
    nacos:
      server-addr: 192.168.1.135:8848
    openfeign:
      okhttp:
        enabled: true
  data:
    redis:
      host: 192.168.1.135
      port: 6379
      password: 123456
      timeout: 5000
      database: 10

  jackson:
    property-naming-strategy: SNAKE_CASE

  mail:
    host: smtp.example.com
    port: 587
    username: your@email.com
    password: yourpassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hwadee.IOTS_SCS.entity.POJO
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: "nakl24rsjfhhrla8u24325ha"
  expiration: 86400000

server:
  port: 0

log4j:
  rootLogger: debug,stdout
  appender:
    stdout: org.apache.log4j.ConsoleAppender
    # Target: System.err （如需要可以取消注释）
    layout: org.apache.log4j.SimpleLayout
