spring:
  application:
    name: IOTS_SCS_backend

  datasource:
    url: jdbc:mysql://localhost:3306/smart_study?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: test

  data:
    redis:
      host: 192.168.2.98
      port: 6379
      password: hwadee
      timeout: 5000
      database: 10

  jackson:
    property-naming-strategy: SNAKE_CASE

  mail:
    host: smtp.qq.com               # 邮件服务器地址，例如 QQ 邮箱
    port: 587
    username: system@yourdomain.com  # 邮箱
    password: 1111111          # 不是邮箱密码，是授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true




mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hwadee.IOTS_SCS.entity.POJO
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.hwadee.IOTS_SCS.util


jwt:
  secret: "nakl24rsjfhhrla8u24325ha"
  expiration: 86400000

server:
  port: 8080

log4j:
  rootLogger: debug,stdout
  appender:
    stdout: org.apache.log4j.ConsoleAppender
    # Target: System.err （如需要可以取消注释）
    layout: org.apache.log4j.SimpleLayout
