server:
  port: 0 #随机端口
spring:
  application:
    name: learn-service #服务名（注册在NACOS的服务名）
  cloud:
    nacos:
      server-addr: ${NACOS_IP:127.0.0.1}:${NACOS_PORT:8848} # nacos地址 NACOS_IP/NACOS_PORT是环境变量
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD_IP:127.0.0.1}:${SENTINEL_DASHBOARD_PORT:8090} # sentinel控制台地址
        port: ${SENTINEL_COMMUNICATE_PORT:8719}
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          ai-service:
            connect-timeout: 300000
            read-timeout: 300000
  datasource:
    url: jdbc:mysql://${MYSQL_IP:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:learn_center}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.csu.learn.controller  # 扫描的包，用于自动发现API