server:
  port: 0 #随机端口
spring:
  application:
    name: knowledge-service #服务名（注册在NACOS的服务名）
  cloud:
    nacos:
      server-addr: ${NACOS_IP:127.0.0.1}:${NACOS_PORT:8848} # nacos地址 NACOS_IP/NACOS_PORT是环境变量
    openfeign:
      okhttp:
        enabled: true
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD_IP:127.0.0.1}:${SENTINEL_DASHBOARD_PORT:8090} # sentinel控制台地址
        port: ${SENTINEL_COMMUNICATE_PORT:8719}
  datasource:
    url: jdbc:mysql://${MYSQL_IP:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:knowledge}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: ${REDIS_IP:127.0.0.1}
      port: ${REDIS_PORT:6379}       # Redis 端口（默认 6379）
      password: ${REDIS_PASSWORD:123456} # Redis 密码（若未设置密码，可省略）
      database: ${REDIS_DB:0}      # 数据库索引（默认 0，Redis 支持 16 个数据库）
      timeout: 3000ms  # 连接超时时间（毫秒）
      # Lettuce 连接池配置（可选，推荐配置以提高性能）
      lettuce:
        pool:
          max-active: 8   # 最大连接数（默认 8）
          max-idle: 8     # 最大空闲连接数（默认 8）
          min-idle: 2     # 最小空闲连接数（默认 0）
          max-wait: -1ms  # 最大阻塞等待时间（-1 表示无限制）
  elasticsearch:
    uris: http://${ES_IP:127.0.0.1}:${ES_PORT:9200}  # ES地址
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.csu.knowledge.controller  # 扫描的包，用于自动发现API
csu:
  knowledge:
    es-ip: ${ES_IP:127.0.0.1}
    es-port: ${ES_PORT:9200}
    index-name: knowledge-base

file:
  store:
    path: E:/temp/app/knowledge/